### ISSUE TITLE
The code worked?

### ISSUE THREAD

**Issue by GTron-1729** [xsephtion/HENNGE-Challenge#1]
hey @xsephtion, the python code that you have uploaded for sending the HTTP POST request, did you had a successful authorization? All I get is unauthorized access in my case.

**Comment by xsephtion** [comment]
> hey @xsephtion, the python code that you have uploaded for sending the HTTP POST request, did you had a successful authorization? All I get is unauthorized access in my case.

Yes I had a successful authorization. Try to change your secret if you're having unauthorized access.

**Comment by GTron-1729** [comment]
Awesome @xsephtion, So did you get an interview with them?
