### ISSUE TITLE
Sending via Postman not working

### ISSUE THREAD

**Issue by GoodnessEzeh** [xsephtion/HENNGE-Challenge#2]
Hello! I tried sending the request via Postman just like you did but it returned {
    "message": "Invalid auth type for this challenge, please check it and try again"
}. I used Basic Authentication for but I'm wondering what went wrong?

**Comment by hafizip00** [comment]
@xsephtion I'm facing same issue of authorization  can you please guide me how to get authorized with my challenge?

**Comment by xsephtion** [comment]
> @xsephtion I'm facing same issue of authorization can you please guide me how to get authorized with my challenge?

This repository is already 4 years old. I might be wrong, but they might changed the process on how to authorize.

**Comment by hafizip00** [comment]
I figured that out and I sent the request and it accepted. Thanks for response

**Comment by hafizip00** [comment]
I figured that out and I sent the request and it accepted. Thanks for response
